general {
    hide_cursor = true
}
background {
    path = screenshot
    blur_passes = 3
}
input-field {
    size = 0, 70
    outline_thickness = 2
    inner_color = rgba(29, 32, 33, 1.0)
    outer_color = rgba(83a598ee) rgba(d3869bee) 45deg
    check_color = rgba(83a598ee) rgba(d3869bee) 120deg
    font_family = JetBrainsMono Nerd Font
    font_color = rgb(142, 192, 124)
    fade_on_empty = true
    position = 0, -60
}
label {
    text = Hi there, $USER
    color = rgba(142, 192, 124, 1.0)
    font_size = 20
    font_family = JetBrainsMono Nerd Font Bold Italic
    position = 0, 10
    halign = center
    valign = center
}
label {
    text = $TIME
    color = rgba(184, 187, 38, 1.0)
    font_size = 150
    font_family = JetBrainsMono Nerd Font Extrabold
    position = 0, 200
    halign = center
    valign = center
}
